Create Database CaseStudy_1

Use CaseStudy_1
select * from fact
select * from Location
select * from product
--1)Display the number of states present in the LocationTable-- Count the number of unique states in the location table
SELECT COUNT(DISTINCT state) AS NumberOfStates
FROM location;--2) How many products are of regular type ?SELECT COUNT(*) AS RegularProducts
FROM Product
WHERE Type = 'Regular';--3) How much spending has been done on marketing of product id 1SELECT SUM(Marketing) AS TotalMarketing
FROM fact
WHERE ProductId = 1;--4) What is the minimum sales of a product ?SELECT MIN(Sales) AS MinimumSales
FROM fact;--5) Display max Cost of Good Sold(COGS).SELECT MAX(COGS) AS MaximumCOGS
FROM fact;

--6) Display the Details of the product where product type is coffeeSELECT * FROM Product WHERE Product_Type='COFFEE'--7) Display the details where total_expenses is greater than 40.SELECT * FROM fact WHERE Total_Expenses>40 --8) What is the average sales in Area_Code 719 ?SELECT AVG(Sales)  FROM fact WHERE Area_Code=719--9) Find out the total profit generated by Colorado state.--Fact, LocationSELECT STATE,SUM(Profit) FROM FACT AS FINNER JOIN LOCATION AS LON F.Area_Code=L.Area_CodeGROUP BY STATEHAVING STATE = 'COLORADO'--10) Display the average inventory for each product id.SELECT ProductId, AVG(Inventory) FROM FACTGROUP BY ProductId ORDER BY ProductID

--11. Display the state in a sequential order in a location table
select distinct State from location order by state DESC